version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-receipts_db}
      POSTGRES_USER: ${POSTGRES_USER:-receipts_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-receipts_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-receipts_user} -d ${POSTGRES_DB:-receipts_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django_app
    command: bash -c "python manage.py migrate && gunicorn lab7.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-receipts_user}:${POSTGRES_PASSWORD:-receipts_pass}@db:5432/${POSTGRES_DB:-receipts_db}
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: