# Generated by Django 5.2 on 2025-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cashier', 'Кассир'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='cashier', max_length=10),
        ),
    ]
